export interface ServerMetrics {
  cpuUsagePercent: number,
  totalDiskSpaceInBytes: number,
  remainingDiskSpaceInBytes: number,
  savedScreenshotsSizeInBytes: number,
  savedVideosSizeInBytes: number,
  maxAvailableMemoryInBytes: number,
  totalUsedMemoryInBytes: number,
  diagramBackgroundColor: string,
  diagramTextColor: string,
  cpuUtilisationColor: string,
  diskUsageScreenshotColor: string,
  diskUsageVideoColor: string,
  diskUsageOtherColor: string,
  memoryUtilisationColor: string,
}
