@startuml
left to right direction

cloud INET {
    rectangle " " #line:transparent {
        () uploadScreenshot
        () "getExaminees"
        () "getScreenshot"
        () "downloadVideo"
    }

    "uploadScreenshot" -- [Franklyn Server]
    "getExaminees" -- [Franklyn Server]
    "getScreenshot" -- [Franklyn Server]
    "downloadVideo" -- [Franklyn Server]
}

package LAN {
    package Examinees {
        [OpenBox1] --( "uploadScreenshot"
        [OpenBox2] --( "uploadScreenshot"
        [OpenBox3] --( "uploadScreenshot"
    }

    node Instructors {
        [Instructor Frontend] <<browser>>
    }
}
[Instructor Frontend] --( "getExaminees"
[Instructor Frontend] --( "getScreenshot"
[Instructor Frontend] --( "downloadVideo"

" " -[hidden]- INET
LAN -[hidden]- " "
@enduml
